### ISSUE TITLE
Other versions

### ISSUE THREAD

**Issue by Wronschien** [SuiMachine/Red-Faction-2---Widescreen-fixer#1]
Hello, the fix doesn't work on French retail version, even though it does recognize the game has started.
Is there anything that can be done to adapt it ?
Thank you

**Comment by SuiMachine** [comment]
Not available via Steam :(

**Comment by Wronschien** [comment]
Thanks for the reply, well I can provide you with an iso of my disc if you want ?

**Comment by SuiMachine** [comment]
If you have it somewhere, I might have a look then.

**Comment by Wronschien** [comment]
Alright, [here](https://drive.google.com/file/d/1yy5DBQ9NNcQEgBbZHlr9plHIsheIHaIh/view?usp=sharing) it is

**Comment by SuiMachine** [comment]
Will try and have a look tomorrow or on Saturday.

**Comment by Wronschien** [comment]
The game is 20 years old, I can wait some more :)

**Comment by SuiMachine** [comment]
Reworked. Although I have no idea how you have got this to run, cause I literally had to edit instructions in the exe to get past some errors. If you use some community patch - it probably won't work though and will need more work:
https://github.com/SuiMachine/Red-Faction-2---Widescreen-fixer/releases/tag/0.8

**Comment by Wronschien** [comment]
Great !!
I'm sorry I was so long to react but the notification email was sent to spams… Anyway, thank you very much for taking the time to have a look in my problem and fixing it. Actually I simply use dgvoodoo with D3D12 feature level 12, and the game runs quite well.
